# Homework 2
Geometry Analysis Project: determine the bond lengths between each atom in a water molecule

In [1]:
import numpy
import os

In [82]:
# read the data, skip the first 2 header since we don't really need them

water_file = os.path.join('data','water.xyz')
data = numpy.genfromtxt(fname = water_file, skip_header = 2, delimiter = '' , dtype = 'unicode')
print(data)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [121]:
# separate the atoms (strings) and the coordinates (cast data string to float)

atoms = data[:,0]
coord = data[:,1:].astype(numpy.float)

num_rows = len(atoms) # = number of atoms

print(coord)
print(atoms)
#print(num_atoms)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
['O' 'H1' 'H2']


In [122]:
# test loop

for i in range(0,num_rows):
    for j in range(0, num_rows):
        y_diff_sqrd = coord[i,1] - coord[j,1]
        print(F' y[{atoms[i]}]1 - y[{atoms[j]}]2 = {y_diff_sqrd}')
        

 y[O]1 - y[O]2 = 0.0
 y[O]1 - y[H1]2 = -0.008642
 y[O]1 - y[H2]2 = -0.9381820000000001
 y[H1]1 - y[O]2 = 0.008642
 y[H1]1 - y[H1]2 = 0.0
 y[H1]1 - y[H2]2 = -0.92954
 y[H2]1 - y[O]2 = 0.9381820000000001
 y[H2]1 - y[H1]2 = 0.92954
 y[H2]1 - y[H2]2 = 0.0


In [128]:
# loop to obtain the distance/bond length between each coordinates using distance formula

for i in range(0, num_rows):
    for j in range(0, num_rows):
        
        # take the difference between the x's, y's, and the z's and square each
        x_diff_sqrd = (coord[i,0] - coord[j,0])**2
        y_diff_sqrd = (coord[i,1] - coord[j,1])**2
        z_diff_sqrd = (coord[i,2] - coord[j,2])**2
        
        #sum of the squares
        xyz_sum = x_diff_sqrd + y_diff_sqrd + z_diff_sqrd

        distances = numpy.sqrt(xyz_sum)
        
        #print(distances)
        print(F'{atoms[i]}\tto\t{atoms[j]}\t:\t{distances:.3f}')

O	to	O	:	0.000
O	to	H1	:	0.969
O	to	H2	:	0.969
H1	to	O	:	0.969
H1	to	H1	:	0.000
H1	to	H2	:	1.527
H2	to	O	:	0.969
H2	to	H1	:	1.527
H2	to	H2	:	0.000
